server:
  servlet:
    port: ${PORT}
    contextPath: /
debug: true
spring:

  application:
    name: FoodOrderingApp-api

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ec2-52-45-179-101.compute-1.amazonaws.com:5432/d2aar5q7os63g1
    username: ${USERNAME}
    password: ${PASSWORD}

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect