server:
  servlet:
    port: ${PORT}
    contextPath: /
debug: true
spring:

  application:
    name: FoodOrderingApp-api

  datasource:
    hikari:
        minIdle: 10
        idle-timeout: 10000
        maximumPoolSize: 5
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://mouse.db.elephantsql.com/tzwhcyns
    username: tzwhcyns
    password: mWmaAF8VHt-z4j0jXzdoQFpYmscFExhK

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
